app/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns

from app.views import *


urlpatterns = [
    url(r'get$', ModelView.as_view(), name='model_get'),
    url(r'get/(?P<model>\w+)/$', ObjectView.as_view(), name='object_url'),
    url(r'get/(?P<model>\w+)/(?P<pk>[0-9]+)/$', ObjectDetailView.as_view(), name='detail_url'),
    url(r'create_point/$', CreatePoint.as_view(), name="create_point"),
    url(r'create_pointtype/$', CreatePointType.as_view(), name="create_pointtype"),
    url(r'update_point/(?P<id>[0-9]+)/$', UpdatePoint.as_view(), name='update_point'),
    url(r'update_pointtype/(?P<id>[0-9]+)/$', UpdatePointType.as_view(), name='update_pointtype'),
    url(r'^delete_point/(?P<pk>\d+)/$', PointDelete.as_view(), name="delete_point"),
    url(r'^delete_pointtype/(?P<pk>\d+)/$', PointTypeDelete.as_view(), name="delete_pointtype"),
    # url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^points/', PointList.as_view()),

]
# urlpatterns = format_suffix_patterns(urlpatterns)

test_project/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

import app
from app.views import *



# i18n_urls = (
#     url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
# )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.urls', namespace='myapp')),
]

# urlpatterns.extend(i18n_patterns(*i18n_urls, prefix_default_language=False))

app/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
from django.urls import reverse


class PointType(models.Model):
    name = models.CharField(max_length=20, verbose_name=_(u'Имя типа точки'))
    description = models.CharField(max_length=20, verbose_name=_(u'Описание'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myapp:detail_url', kwargs={'model': 'pointtype', 'pk': self.id})


class Point(models.Model):
    name = models.CharField(max_length=20, verbose_name=_(u'Имя точки'))
    code = models.CharField(max_length=20, verbose_name=_(u'Код точки'))
    address = models.CharField(max_length=20, verbose_name=_(u'Адрес точки'))
    type = models.ForeignKey(PointType)
    latitude = models.DecimalField(max_digits=19, decimal_places=10, verbose_name=_(u'Широта'))
    longitude = models.DecimalField(max_digits=19, decimal_places=10, verbose_name=_(u'Долгота'))

    def __str__(self):
        return self.name

    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('myapp:detail_url', kwargs={'model': 'point', 'pk': self.id})

app/forms.py
from django import forms

from app.models import Point, PointType


class PointCreateForm(forms.ModelForm):
    class Meta:
        model = Point
        exclude = ['']

class PointTypeCreateForm(forms.ModelForm):
    class Meta:
        model = PointType
        exclude = ['']

app/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.apps import apps
from rest_framework.response import Response
from rest_framework.views import APIView

from app.forms import PointCreateForm, PointTypeCreateForm
from app.models import Point, PointType
from app.serializers import PointSerializer

# Api для получения данных по точкам
class PointList(APIView):
    def get(self, request):
        points = Point.objects.all()
        serializer = PointSerializer(points, many=True)
        return Response(serializer.data)

# Вывод списка моделей
class ModelView(TemplateView):
    template_name = 'models.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        models = apps.all_models['app']  # returns dict with all models you defined
        data['models'] = models
        return data


# Вывод списка объектов выбранной модели
class ObjectView(ListView):
    template_name = 'objects.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['model'] = self.kwargs['model']
        return data

    def get_queryset(self):
        qs = apps.all_models['app'][self.kwargs['model']].objects.all()
        return qs


# Вывод информации о выбранном объекте
class ObjectDetailView(TemplateView):
    template_name = 'object_detail.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        qs = apps.all_models['app'][self.kwargs['model']].objects.filter(pk=self.kwargs['pk'])
        data['qs'] = qs.values()[0]
        data['model'] = self.kwargs['model']
        return data


# Создание нового объекта класса Point
class CreatePoint(CreateView):
    template_name = 'form.html'
    model = Point
    form_class = PointCreateForm


# Создание нового объекта класса PointType
class CreatePointType(CreateView):
    template_name = 'form.html'
    model = PointType
    form_class = PointTypeCreateForm


class UpdatePoint(UpdateView):
    template_name = 'form.html'
    form_class = PointCreateForm

    def get_object(self, queryset=None):
        id = self.kwargs.get("id")
        return get_object_or_404(Point, id=id)


class UpdatePointType(UpdateView):
    template_name = 'form.html'
    form_class = PointTypeCreateForm

    def get_object(self, queryset=None):
        id = self.kwargs.get("id")
        return get_object_or_404(PointType, id=id)


class PointDelete(DeleteView):
    template_name = 'delete.html'
    model = Point
    success_url = reverse_lazy('myapp:object_url', kwargs={"model": 'point'})


class PointTypeDelete(DeleteView):
    template_name = 'delete.html'
    model = PointType
    success_url = reverse_lazy('myapp:object_url', kwargs={"model": 'pointtype'})

app/templates/delete.html
{% load i18n %}
<form action="" method="post">{% csrf_token %}
    <p>{% blocktrans %}Are you sure you want to delete "{{ object }}" {% endblocktrans %}?</p>
    <input type="submit" value="Confirm" />
</form>

app/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

</body>
</html>

app/templates/models.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load i18n %}
    {% trans "List of models" %}





    <ul>
        {% for model in models %}
        <li><a href="{% url 'myapp:object_url' model %}">{{ model }}</a></li>
        {% endfor %}
    </ul>

</body>
</html>

app/templates/object_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load i18n %}
<div>
{% trans "Object description" %}
</div>
<div style="display:inline-block">
    <table>
    {% for f  in qs %}
    <tr>
        <td>{{ f }}</td>
    </tr>
    {% endfor %}
</table>
</div>
<div style="display:inline-block">
<table>
    {% for f  in qs.values %}
    <tr>
        <td>{{ f }}</td>
    </tr>
    {% endfor %}
</table>
</div>
<div>
{% if model == "point" %}
    <a href="{% url 'myapp:create_point' %}">{% trans "Create" %}</a>
    <a href="{% url 'myapp:update_point' qs.id %}">{% trans "Update" %}</a>
    <a href="{% url 'myapp:delete_point' qs.id %}">{% trans "Delete" %}</a>
{% elif model == "pointtype" %}
    <a href="{% url 'myapp:create_pointtype' %}">{% trans "Create" %}</a>
    <a href="{% url 'myapp:update_pointtype' qs.id %}">{% trans "Update" %}</a>
    <a href="{% url 'myapp:delete_pointtype' qs.id %}">{% trans "Delete" %}</a>
{% endif %}
</div>
</body>
</html>

app/templates/objects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

   <ul>
       {% for obj in object_list %}
       <li><a href="{% url 'myapp:detail_url' model obj.id %}">{{ obj.name }}</a></li>
       {% endfor %}
   </ul>

</body>
</html>